# Extending the hospital-insurance mapping to include Hospital 2
import pandas as pd

insurance_col = pd.read_csv()

hospital_insurance_mapping = {
    "Hospital 1": [
        "Aetna",
        "Aetna Medicare Advantage HMO/POS/PPO",
        "Anthem Managed Medicaid - Hoosier Care Connect (HCC), Hoosier Healthwise (HHW) & Healthy Indiana Plan",
        "Anthem PPO/HMO",
        "Anthem Medicare Advantage PPO/HMO",
        "Blue Cross and Blue Shield",
        "CareSource Managed Medicaid - HHW & HIP",
        "CareSource Marketplace",
        "CIGNA HealthCare PPO/HMO",
        "Cofinity (Aetna) PPOM/PPO",
        "Community Health Alliance",
        "Community Health Direct Gold/Sliver",
        "Deaconess OneCare",
        "Encore Health Network PPO",
        "EncoreCombined",
        "First Health Network",
        "Humana ChoiceCare",
        "Humana Medicare Advantage HMO/PPO",
        "IU Health Plans",
        "IU Health Plans Medicare Advantage HMO",
        "IU Health Plans - IU Health Employee Plan",
        "Lutheran Preferred",
        "Medicaid (Traditional)",
        "Medicare (Traditional)",
        "MultiPlan/PHCS",
        "Parkview Signature Care PPO/EPO",
        "Pakota Valley",
        "Physicians Health Plan of Northern Indiana (PHP)",
        "Sagamore Health Network",
        "SHO Direct",
        "Southern Indiana Health Organization (SIHO) Inspire/PPO",
        "UnitedHealthCare",
        "UnitedHealthCare Medicare Advantage HMO/POS/PPO",
        "VA Community Care Network"
    ],
    "Hospital 2": [
        "Aetna",
        "Aetna Whole Health",
        "Coordinated Care Ambetter",
        "BridgeSpan (RealValue)",
        "CHPW -Cascade Select",
        "Kitsap County - Specialist only",
        "Cigna",
        "Coventry/First Health",
        "First Choice Health Network",
        "Humana/ChoiceCare",
        "Kaiser Permanente Core",
        "Partial",
        "Kaiser Permanente CoreSelect",
        "Kaiser Permanente Virtual Plus",
        "Kaiser Permanente Access PPO",
        "Kaiser Permanente Summit PPO",
        "LifeWise",
        "LifeWise Primary",
        "LifeWise Preferred",
        "Molina Marketplace",
        "Multiplan/PHCS",
        "Premera Blue Cross",
        "Premera Heritage Prime",
        "Kitsap Co. Clinics",
        "Premera Heritage Signature",
        "Regence Blue Shield",
        "Regence VMFH AHN",
        "Regence Individual & Family",
        "Uniform Medical Plan (UMP)",
        "UMP Plus - PSHVN",
        "United Healthcare (UHC)",
        "UHC Doctors Plan",
        "UHC Nexus ACO",
        "UHC Navigate",
        "UHC Charter"
    ]
}

